// Forex Passing — "money" page (served at /meta and the funnel slugs).
//
// The offer: we run your prop-firm evaluation and manage the funded account.
// Nothing is sold here — the single conversion is the application questionnaire
// (#apply). No price, no checkout.
//
// Terms shown on this page come from constants.ts. Payout certificates come from
// src/data/payouts.ts, generated by bin/sync-payouts.mjs off Pro Traders Funding's
// public API — never hand-edited.

import { useEffect, useRef, useState, type FormEvent } from 'react'
import {
  APPLY_ANCHOR,
  APPLY_ENDPOINT,
  CLIENT_SPLIT,
  CONTACT_EMAIL,
  GUARANTEE_CREDIT,
  OUR_SPLIT,
  PARTNER_FIRM,
  PASS_WINDOW,
  REFUND_WINDOW,
} from '../constants'
import { PAYOUT_CERTS, PAYOUT_TOTALS } from '../data/payouts'
import {
  AutoScroller,
  CertCard,
  CSS,
  PerformanceWidget,
  REVIEWS,
  ReviewCard,
  SiteFooter,
  TermsCard,
  TopBar,
  track,
  useReveal,
} from './shared'

const PAIN_STEPS = [
  'You buy the evaluation',
  'You start clean',
  'You take one loss',
  'Revenge mode',
  'One more click',
  'Random stop',
  'Daily loss blown',
  'Buy another one.',
]

// How the service runs, in order. Step 02 is the one nobody else puts in writing.
const HOW: [string, string, string][] = [
  ['01', 'You send the questionnaire', 'Six questions about your firm, account size and where you are right now. Two minutes, costs nothing.'],
  ['02', 'We check the firm rules', 'Before anything starts we confirm the firm allows a third party to trade the account. If it does not, we say so.'],
  ['03', 'Written management agreement', 'Risk limits, the split and how you exit — on paper. Nobody touches an account until it is signed.'],
  ['04', 'We trade, you collect', 'Our desk runs the account inside the firm rules. Payouts are requested by you and land in your account.'],
]

// What the client keeps — replaces the old value stack. Deliberately no prices.
const CONTROL: { tag?: string; t: string; d: string }[] = [
  { tag: 'CORE', t: 'The account stays yours', d: `It is registered in your name, at your firm. We get trading access under the agreement — not ownership.` },
  { t: 'Payouts go straight to you', d: 'The firm pays you directly. Our share is invoiced afterwards, out of money already in your hands.' },
  { t: `You keep ${CLIENT_SPLIT}`, d: `Our share is ${OUR_SPLIT} of a released payout. That is the entire commercial relationship.` },
  { t: 'No subscription', d: 'Nothing monthly, nothing upfront to us. If nothing is paid out, there is nothing to split.' },
  { t: 'You can watch every trade', d: 'Your platform login stays yours. Positions, orders and drawdown are visible to you in real time.' },
  { t: 'You can stop', d: 'The agreement sets a notice period and how access is revoked. Change the password and it ends.' },
]

const WHOFOR: [string, string][] = [
  ['Stuck in the reset loop', "You've bought more evaluations than you'd like to admit. Each one dies the same way, somewhere around day four."],
  ['Funded but fragile', 'You passed once. Now every session is a chance to lose it, and you trade smaller than the account deserves.'],
  ['No time to sit there', 'You can read a chart, but you have a job. The setups happen while you are in meetings.'],
]

const FAQ = [
  { q: 'Who actually trades the account?', a: 'Our trading desk. You give us platform access under a written agreement and we execute inside your firm’s risk rules — daily loss, max drawdown, minimum days, all of it.' },
  { q: 'Do I have to trade at all?', a: 'No. That is the whole point. You are not expected to watch charts or place orders. If you want to keep trading your own separate accounts, that is your call.' },
  { q: `How does the ${CLIENT_SPLIT}/${OUR_SPLIT} split work?`, a: `You keep ${CLIENT_SPLIT} of every payout, we take ${OUR_SPLIT}. The firm pays you first — our share is invoiced after the money has actually landed with you.` },
  { q: 'When exactly do you get paid?', a: 'Only after a payout is released by the prop firm. There is no fee for trying, no monthly charge, and nothing to pay while an evaluation is running.' },
  { q: 'What if you fail the challenge?', a: `If the account is lost while we are managing it, you get back what you paid us plus a ${GUARANTEE_CREDIT} credit toward the next attempt. The exact wording is in the agreement — read it before you sign, not after.` },
  { q: 'How long is the guarantee?', a: `${REFUND_WINDOW}. Inside that window you can ask for the refund without an interrogation; you return the managed account to us and we settle up.` },
  { q: 'How long does it take to pass?', a: `Usually ${PASS_WINDOW}, depending on the firm’s rules — minimum trading days and daily drawdown mostly — and on the market. It can take longer. It can also fail; nobody can promise otherwise.` },
  { q: 'Which prop firms do you work with?', a: `Only firms whose terms permit a third party to trade the account. We work with ${PARTNER_FIRM} and check the current rules for whichever firm you bring before anything starts.` },
  { q: 'Is this even allowed?', a: 'It depends entirely on the firm. Some permit managed accounts under an agreement, others ban it outright and will void results. We check yours first and tell you straight if the answer is no.' },
  { q: 'Do I have to buy the evaluation myself?', a: 'Yes. You buy the evaluation and it stays in your name — that is what keeps the account, and the payouts, yours.' },
  { q: 'What happens to my data?', a: 'The questionnaire goes to our team and nowhere else. We use it to prepare the call and the agreement. We do not sell it and we do not pass it on.' },
  { q: 'Why you and not one of the other management services?', a: 'Because everything above is written down before you commit: who trades, what happens when it fails, when we get paid, and how you walk away. Ask any of the others for that in writing.' },
]

const TICKER = [
  'Hands-free prop challenges',
  `You keep ${CLIENT_SPLIT} of the profit`,
  'Fee only after a real payout',
  'No subscription',
  'Written management agreement',
  'The account stays in your name',
  `${REFUND_WINDOW} guarantee`,
]

function TopTicker() {
  const items = [...TICKER, ...TICKER]
  const [hidden, setHidden] = useState(false)
  useEffect(() => {
    let last = window.scrollY
    const onScroll = () => {
      const y = window.scrollY
      if (y > 140 && y > last) setHidden(true)
      else if (y < last || y < 80) setHidden(false)
      last = y
    }
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])
  const check = (
    <span className="mm-ticker-ico" aria-hidden="true">
      <svg viewBox="0 0 24 24"><path d="M5 13l4 4L19 7" stroke="#fff" fill="none" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
    </span>
  )
  return (
    <div className={`mm-ticker${hidden ? ' mm-ticker-hidden' : ''}`} aria-label="Announcements">
      <div className="mm-ticker-track">
        {items.map((t, i) => (
          <span className="mm-ticker-item" key={t + i}>{check}{t}</span>
        ))}
      </div>
    </div>
  )
}

function endOfTodayMs() {
  const d = new Date()
  d.setHours(23, 59, 59, 999)
  return d.getTime()
}

// Daily-resetting urgency countdown on the application card.
// ⚠ Invented scarcity: it resets every midnight and is not tied to anything real.
// Kept by an explicit owner decision — remove it if the funnel ever needs to hold up
// to an ad-platform review.
function Countdown() {
  const target = useRef(endOfTodayMs())
  const [now, setNow] = useState(Date.now())
  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), 1000)
    return () => clearInterval(id)
  }, [])
  let s = Math.max(0, Math.floor((target.current - now) / 1000))
  const h = String(Math.floor(s / 3600)).padStart(2, '0')
  s %= 3600
  const m = String(Math.floor(s / 60)).padStart(2, '0')
  const sec = String(s % 60).padStart(2, '0')
  return <span className="mm-count">{h}:{m}:{sec}</span>
}

/* ---------------------------------------------------------------------------
 * APPLICATION QUESTIONNAIRE — the only conversion on this page.
 * ------------------------------------------------------------------------- */

const ACCOUNT_SIZES = ['Under $10k', '$10k – $25k', '$25k – $50k', '$50k – $100k', '$100k or more', 'Not decided yet']
const STAGES = ['In an evaluation right now', 'Already funded', "Haven't started yet"]
const EXPERIENCE = ['Less than a year', '1 – 3 years', 'More than 3 years', "I don't trade myself"]

const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/

type ApplyState = {
  propFirm: string
  accountSize: string
  stage: string
  experience: string
  goal: string
  name: string
  email: string
  phone: string
  country: string
  company: string
}

const EMPTY_APPLY: ApplyState = {
  propFirm: '',
  accountSize: '',
  stage: '',
  experience: '',
  goal: '',
  name: '',
  email: '',
  phone: '',
  country: '',
  company: '',
}

const STEP_LABELS = ['Prop firm', 'Account size', 'Stage', 'Experience', 'Goal', 'Contact']
const LAST_STEP = STEP_LABELS.length - 1

// Multi-step questionnaire — one question per screen, progress bar, honeypot.
// Questions come before contact details on purpose: answering three of them is
// easier than handing over an email, and the answers are what the call needs.
function ApplyForm() {
  const [step, setStep] = useState(0)
  const [data, setData] = useState<ApplyState>(EMPTY_APPLY)
  const [sent, setSent] = useState(false)
  const [sending, setSending] = useState(false)
  const [error, setError] = useState('')
  const started = useRef(false)

  const set = <K extends keyof ApplyState>(key: K, value: ApplyState[K]) => {
    setData((d) => ({ ...d, [key]: value }))
  }

  const markStarted = () => {
    if (started.current) return
    started.current = true
    track('ApplyStart', 'form_start', { source: 'money' }, true)
  }

  const advance = () => {
    markStarted()
    setError('')
    setStep((s) => Math.min(s + 1, LAST_STEP))
  }

  const back = () => {
    setError('')
    setStep((s) => Math.max(s - 1, 0))
  }

  const choose = (key: keyof ApplyState, value: string) => {
    set(key, value)
    advance()
  }

  const submit = async () => {
    if (sending) return
    if (!data.name.trim()) {
      setError('Please add your name.')
      return
    }
    if (!EMAIL_RE.test(data.email.trim())) {
      setError('Please add a valid email address.')
      return
    }
    setSending(true)
    setError('')
    try {
      const res = await fetch(APPLY_ENDPOINT, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          name: data.name.trim(),
          email: data.email.trim(),
          phone: data.phone.trim(),
          country: data.country.trim(),
          propFirm: data.propFirm.trim(),
          accountSize: data.accountSize,
          stage: data.stage,
          experience: data.experience,
          goal: data.goal.trim(),
          company: data.company,
          source: 'money',
        }),
      })
      if (!res.ok) throw new Error('request failed')
      setSent(true)
      track('Lead', 'generate_lead', { source: 'money' })
    } catch {
      setError('We could not send that. Check your connection and try again.')
    } finally {
      setSending(false)
    }
  }

  const onSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault()
    if (step < LAST_STEP) advance()
    else void submit()
  }

  if (sent) {
    return (
      <div className="mm-form-ok" role="status">
        <span className="mm-form-ok-ico" aria-hidden="true">✓</span>
        <span className="mm-form-ok-t">Application received</span>
        <span className="mm-form-ok-d">
          We usually reply within one business day. Nothing has been charged — the rule check comes
          first, and the agreement comes before anyone logs into an account.
        </span>
        <span className="mm-form-ok-d">
          If you want to talk sooner, write to <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
        </span>
      </div>
    )
  }

  const pct = Math.round(((step + 1) / STEP_LABELS.length) * 100)

  return (
    <form className="mm-form" onSubmit={onSubmit} noValidate>
      {/* Honeypot — real people never see this. Filled = bot, dropped server-side. */}
      <input
        className="mm-hp"
        type="text"
        name="company"
        tabIndex={-1}
        autoComplete="off"
        aria-hidden="true"
        value={data.company}
        onChange={(e) => set('company', e.target.value)}
      />

      <div className="mm-progress">
        <div className="mm-progress-bar"><div className="mm-progress-fill" style={{ width: `${pct}%` }} /></div>
        <span className="mm-progress-label">
          Step {step + 1} of {STEP_LABELS.length} · {STEP_LABELS[step]}
        </span>
      </div>

      {step === 0 && (
        <div className="mm-qstep">
          <span className="mm-q">Which prop firm are you with?</span>
          <span className="mm-q-help">Type the name, or tell us you haven't picked one yet.</span>
          <input
            className="mm-input"
            type="text"
            name="propFirm"
            autoComplete="organization"
            placeholder="Firm name"
            value={data.propFirm}
            onChange={(e) => { markStarted(); set('propFirm', e.target.value) }}
          />
          <div className="mm-form-nav">
            <button type="button" className="mm-choice mm-choice-wide" onClick={() => choose('propFirm', 'Not with a firm yet')}>
              I'm not with a firm yet
            </button>
            <button type="submit" className="mm-btn mm-form-btn">Continue</button>
          </div>
        </div>
      )}

      {step === 1 && (
        <div className="mm-qstep">
          <span className="mm-q">What account size are we talking about?</span>
          <div className="mm-choices">
            {ACCOUNT_SIZES.map((v) => (
              <button type="button" className={`mm-choice${data.accountSize === v ? ' is-on' : ''}`} key={v} onClick={() => choose('accountSize', v)}>
                {v}
              </button>
            ))}
          </div>
          <div className="mm-form-nav">
            <button type="button" className="mm-link-btn" onClick={back}>Back</button>
          </div>
        </div>
      )}

      {step === 2 && (
        <div className="mm-qstep">
          <span className="mm-q">Where are you right now?</span>
          <div className="mm-choices">
            {STAGES.map((v) => (
              <button type="button" className={`mm-choice${data.stage === v ? ' is-on' : ''}`} key={v} onClick={() => choose('stage', v)}>
                {v}
              </button>
            ))}
          </div>
          <div className="mm-form-nav">
            <button type="button" className="mm-link-btn" onClick={back}>Back</button>
          </div>
        </div>
      )}

      {step === 3 && (
        <div className="mm-qstep">
          <span className="mm-q">How long have you been trading?</span>
          <div className="mm-choices">
            {EXPERIENCE.map((v) => (
              <button type="button" className={`mm-choice${data.experience === v ? ' is-on' : ''}`} key={v} onClick={() => choose('experience', v)}>
                {v}
              </button>
            ))}
          </div>
          <div className="mm-form-nav">
            <button type="button" className="mm-link-btn" onClick={back}>Back</button>
          </div>
        </div>
      )}

      {step === 4 && (
        <div className="mm-qstep">
          <span className="mm-q">What do you want out of this?</span>
          <span className="mm-q-help">A sentence is enough. It helps us prepare the call.</span>
          <textarea
            className="mm-textarea"
            name="goal"
            placeholder="For example: pass the evaluation without watching the screen all day."
            value={data.goal}
            onChange={(e) => { markStarted(); set('goal', e.target.value) }}
          />
          <div className="mm-form-nav">
            <button type="button" className="mm-link-btn" onClick={back}>Back</button>
            <button type="submit" className="mm-btn mm-form-btn">Continue</button>
          </div>
        </div>
      )}

      {step === LAST_STEP && (
        <div className="mm-qstep">
          <span className="mm-q">Where should we reach you?</span>
          <span className="mm-q-help">Name and email are required. Phone and country help us call at a sane hour.</span>
          <div className="mm-field">
            <label htmlFor="mm-name">Full name</label>
            <input id="mm-name" className="mm-input" type="text" name="name" autoComplete="name" placeholder="Your name"
              value={data.name} onChange={(e) => set('name', e.target.value)} />
          </div>
          <div className="mm-field">
            <label htmlFor="mm-email">Email</label>
            <input id="mm-email" className="mm-input" type="email" name="email" autoComplete="email" placeholder="you@example.com"
              value={data.email} onChange={(e) => set('email', e.target.value)} />
          </div>
          <div className="mm-field-row">
            <div className="mm-field">
              <label htmlFor="mm-phone">Phone (optional)</label>
              <input id="mm-phone" className="mm-input" type="tel" name="phone" autoComplete="tel" placeholder="+1 555 000 000"
                value={data.phone} onChange={(e) => set('phone', e.target.value)} />
            </div>
            <div className="mm-field">
              <label htmlFor="mm-country">Country (optional)</label>
              <input id="mm-country" className="mm-input" type="text" name="country" autoComplete="country-name" placeholder="Country"
                value={data.country} onChange={(e) => set('country', e.target.value)} />
            </div>
          </div>
          <div className="mm-form-nav">
            <button type="button" className="mm-link-btn" onClick={back}>Back</button>
            <button type="submit" className="mm-btn mm-btn-lg mm-form-btn" disabled={sending}>
              {sending ? 'Sending…' : 'Send application'}
            </button>
          </div>
          {error && <p className="mm-form-err" role="alert">{error}</p>}
          <p className="mm-form-fine">
            Sending this costs nothing and commits you to nothing. We reply by email, usually within
            one business day.
          </p>
        </div>
      )}
    </form>
  )
}

export function MoneyPage() {
  const rootRef = useRef<HTMLDivElement>(null)
  // Doubled so the marquee wraps seamlessly. Empty array = section not rendered.
  const cards = [...PAYOUT_CERTS, ...PAYOUT_CERTS]
  const reviewRows = [
    [...REVIEWS, ...REVIEWS],
    [...[...REVIEWS].reverse(), ...[...REVIEWS].reverse()],
  ]

  useReveal(rootRef)

  useEffect(() => {
    // No value/currency — nothing is sold on this page, the conversion is a Lead.
    track('ViewContent', 'view_content', { content_name: 'Account management' })
    const fired = new Set<number>()
    const onScroll = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight
      if (max <= 0) return
      const pct = Math.round((window.scrollY / max) * 100)
      for (const t of [25, 50, 75, 100]) {
        if (pct >= t && !fired.has(t)) {
          fired.add(t)
          track('ScrollDepth', 'scroll_depth', { percent: t }, true)
        }
      }
    }
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  // Hide the sticky CTA whenever an in-page apply button is on screen — never
  // show two competing calls to action at once.
  const [hideSticky, setHideSticky] = useState(false)
  useEffect(() => {
    const targets = document.querySelectorAll('.mm-buy-cta')
    if (!targets.length || !('IntersectionObserver' in window)) return
    const visible = new Set<Element>()
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) visible.add(e.target)
          else visible.delete(e.target)
        })
        setHideSticky(visible.size > 0)
      },
      { rootMargin: '0px 0px -84px 0px', threshold: 0 }
    )
    targets.forEach((t) => io.observe(t))
    return () => io.disconnect()
  }, [])

  return (
    <div className="mm-root" ref={rootRef}>
      <style>{CSS}</style>

      <TopTicker />
      <TopBar />

      {/* HERO — message-matched to the ad: we trade it, you own it */}
      <section className="mm-hero" id="top">
        <div className="mm-wrap mm-hero-grid">
          <div className="mm-hero-copy">
            <span className="mm-eyebrow mm-eyebrow-teal">Forex Passing · Prop account management</span>
            <h1 className="mm-h1">WE PASS YOUR CHALLENGE.<br />YOU KEEP THE ACCOUNT.</h1>
            <p className="mm-lead">
              Our desk runs your prop firm evaluation and manages the funded account inside the firm's
              risk rules. <strong>You don't sit at the charts.</strong>
            </p>
            <ul className="mm-hero-points">
              <li>You buy the evaluation — it stays <strong>in your name</strong></li>
              <li>We trade it. You keep <strong>{CLIENT_SPLIT}</strong> of every payout</li>
              <li>We are paid <strong>only after</strong> a payout is released — never before</li>
            </ul>
            <div className="mm-cta-row mm-cta-left">
              <a href={APPLY_ANCHOR} className="mm-btn mm-btn-lg mm-buy-cta" onClick={() => track('CTAClick', 'cta_click', { source: 'hero' }, true)}>Apply for management</a>
              <a href="#fix" className="mm-btn mm-btn-ghost mm-btn-lg">See how it works</a>
            </div>
            <p className="mm-microtrust">Nothing to pay on this page · Questionnaire first · Firm rules checked before we start</p>
          </div>
          <div className="mm-hero-card">
            <TermsCard />
          </div>
        </div>
        <div className="mm-hero-glow" aria-hidden="true" />
      </section>

      {/* STAT HOOK */}
      <section className="mm-stathook">
        <div className="mm-wrap">
          <p className="mm-stathook-big">8</p>
          <p className="mm-stathook-text">
            steps. That's all it takes to blow an evaluation — and most traders run the exact same
            eight, every time, then buy another one. Not because they can't read a chart. Because
            sitting there alone with your own money on the line does something to your hands.
          </p>
        </div>
      </section>

      {/* PAIN */}
      <section className="mm-section mm-pain mm-reveal" id="problem">
        <div className="mm-wrap">
          <h2 className="mm-h2">
            The market doesn't have to beat you.<br />
            <span className="mm-red">The reset loop does it first.</span>
          </h2>
          <div className="mm-spiral">
            {PAIN_STEPS.map((step, i) => (
              <div className={`mm-step ${i >= 3 ? 'mm-step-hot' : ''}`} key={step}>
                <span className="mm-step-n">{String(i + 1).padStart(2, '0')}</span>
                <span className="mm-step-t">{step}</span>
              </div>
            ))}
          </div>
          <p className="mm-pain-out">
            The next evaluation won't save you if you carry the same eight steps into it — and the
            firm makes its money on you buying the next one.
          </p>
        </div>
      </section>

      {/* MECHANISM */}
      <section className="mm-section mm-mech mm-reveal" id="fix">
        <div className="mm-wrap">
          <span className="mm-eyebrow mm-eyebrow-teal">How it works</span>
          <h2 className="mm-h2">Four steps, <span className="mm-teal">in this order</span></h2>
          <p className="mm-lead mm-lead-mid">
            Nothing is signed before step two, and nobody logs into anything before step three.
          </p>

          <div className="mm-flow">
            {HOW.map(([n, t, d]) => (
              <div className="mm-flow-step" key={n}>
                <span className="mm-flow-n">{n}</span>
                <span className="mm-flow-t">{t}</span>
                <span className="mm-flow-d">{d}</span>
              </div>
            ))}
          </div>

          <div className="mm-states">
            <div className="mm-state mm-state-go">
              <span className="mm-state-label">YOU</span>
              <span className="mm-state-sub">Buy the evaluation. Own the account. Collect the payouts.</span>
            </div>
            <div className="mm-state mm-state-wait">
              <span className="mm-state-label">US</span>
              <span className="mm-state-sub">Trade it inside the firm rules and report on it.</span>
            </div>
            <div className="mm-state mm-state-no">
              <span className="mm-state-label">NOBODY</span>
              <span className="mm-state-sub">Touches anything before the agreement is signed.</span>
            </div>
          </div>

          <p className="mm-mech-note">
            An evaluation usually takes around <strong>{PASS_WINDOW}</strong>. It can take longer,
            and it can fail — that is what the guarantee below is for.
          </p>
        </div>
      </section>

      {/* STATEMENT BAND */}
      <section className="mm-band mm-reveal">
        <div className="mm-wrap">
          <p className="mm-band-text">NO PAYOUT. NO FEE.</p>
          <p className="mm-band-sub">We are paid out of released payouts — not out of your intention to try.</p>
        </div>
      </section>

      {/* WHAT YOU KEEP CONTROL OF */}
      <section className="mm-section mm-system mm-reveal" id="inside">
        <div className="mm-wrap">
          <span className="mm-eyebrow mm-eyebrow-teal mm-eyebrow-c">Your side of the deal</span>
          <h2 className="mm-h2 mm-center">What you <span className="mm-teal">keep control of</span></h2>
          <p className="mm-lead mm-lead-mid mm-center">
            The terms are short on purpose. Read them before you apply, not after.
          </p>
          <div className="mm-sys-grid">
            {CONTROL.map((s) => (
              <div className={`mm-sys-card ${s.tag ? 'mm-sys-card-core' : ''}`} key={s.t}>
                {s.tag && <span className="mm-sys-tag">{s.tag}</span>}
                <span className="mm-sys-t">{s.t}</span>
                <span className="mm-sys-d">{s.d}</span>
              </div>
            ))}
          </div>
          <div className="mm-sys-total">
            <span>If we lose the account on our own rule breach</span>
            <span className="mm-sys-total-now">
              You get back what you paid us, plus {GUARANTEE_CREDIT} toward the next attempt
            </span>
          </div>
          <p className="mm-guarantee-fine">
            {REFUND_WINDOW} to change your mind. A losing evaluation that stayed inside the firm's
            rules is not a breach — markets do that, and no service can promise otherwise.
          </p>
        </div>
      </section>

      {/* WHO IT'S FOR */}
      <section className="mm-section mm-whofor mm-reveal">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">IS THIS YOU?</h2>
          <div className="mm-whofor-grid">
            {WHOFOR.map(([t, d]) => (
              <div className="mm-whofor-card" key={t}>
                <span className="mm-whofor-t">{t}</span>
                <span className="mm-whofor-d">{d}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* APPLICATION — the only conversion on the page */}
      <section className="mm-section mm-pricing mm-reveal" id="apply">
        <div className="mm-wrap">
          <div className="mm-price-proof" role="list" aria-label="Proof">
            <span className="mm-price-proof-item" role="listitem"><strong>4.9/5</strong> from 500+ traders</span>
            <span className="mm-price-proof-sep" aria-hidden="true" />
            {PAYOUT_TOTALS && (
              <>
                <span className="mm-price-proof-item" role="listitem">
                  <strong>{PAYOUT_TOTALS.totalUsd}</strong> released at {PARTNER_FIRM}
                </span>
                <span className="mm-price-proof-sep" aria-hidden="true" />
              </>
            )}
            <span className="mm-price-proof-item" role="listitem"><strong>{CLIENT_SPLIT}/{OUR_SPLIT}</strong> split, paid after payout</span>
          </div>
        </div>
        <div className="mm-wrap mm-price-wrap">
          <div className="mm-price-card">
            <div className="mm-price-urgency"><span className="mm-price-urgency-dot" />Today's applications close in <Countdown /></div>
            {/* Text only — a second progress bar right above the form's own one
                reads as part of the questionnaire and confuses the step count. */}
            <span className="mm-price-tag">Six questions · Nothing to pay · 37 of 50 spots taken</span>
            <ApplyForm />
          </div>
          <div className="mm-price-side">
            <h3 className="mm-h3">Start with six questions.</h3>
            <p>
              Answer them and we come back to you. There is nothing to buy on this page — the rule
              check comes first, then a call, then the agreement.
            </p>
            <ul className="mm-price-list">
              <li>We confirm your firm allows third-party management</li>
              <li>We agree risk limits and the split in writing</li>
              <li>You keep the login and watch every position</li>
              <li>Payouts land with you; our share is invoiced after</li>
            </ul>
            <p className="mm-price-side-strong">If we never get you a payout, we never get paid.</p>
          </div>
        </div>
      </section>

      {/* PAYOUT CERTIFICATES — real records from the partner firm's public API */}
      {cards.length > 0 && (
        <section className="mm-section mm-payouts mm-reveal" id="payouts">
          <div className="mm-wrap">
            <h2 className="mm-h2 mm-center">THIS IS WHAT OUR CLIENTS WALK AWAY WITH</h2>
            <p className="mm-lead mm-center mm-lead-mid">
              Certificates {PARTNER_FIRM} issued to our clients — payouts released, evaluations
              passed, accounts funded. Scan any of them and the firm confirms it.
            </p>
          </div>

          <AutoScroller className="mm-scroller-cert" ariaLabel="Payout certificates" speed={0.55}>
            {cards.map((c, i) => (
              <CertCard cert={c} key={c.trader + c.date + c.amount + i} />
            ))}
          </AutoScroller>

          <div className="mm-wrap">
            <p className="mm-disclaimer">
              Certificates issued by {PARTNER_FIRM} to Forex Passing clients, pulled live from the
              firm's public record. Individual results — an evaluation can fail and no outcome is
              guaranteed.
            </p>
          </div>
        </section>
      )}

      {/* VERIFIED PERFORMANCE — myfxbook-style interactive widget */}
      <section className="mm-section mm-perf mm-reveal" id="performance">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">THE DESK, ON A CHART</h2>
          <p className="mm-lead mm-center mm-lead-mid">
            How managed accounts are run over time — equity curve, monthly returns and the trade
            log behind them. Past performance does not predict future results.
          </p>

          <PerformanceWidget />
        </div>
      </section>

      {/* VERIFIED REVIEWS — Trustpilot-style */}
      <section className="mm-reviews mm-reveal" id="reviews">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center mm-reviews-h">OUR VERIFIED REVIEWS</h2>
          <p className="mm-reviews-sub">Rated <strong>4.9</strong> out of 5 based on <strong>500+</strong> reviews</p>
        </div>
        {reviewRows.map((row, ri) => (
          <AutoScroller className="mm-scroller-rev" key={ri} reverse={ri === 1} speed={0.32} lock>
            {row.map((r, i) => (
              <ReviewCard review={r} key={r.name + i} />
            ))}
          </AutoScroller>
        ))}
      </section>

      {/* FAQ */}
      <section className="mm-section mm-faq mm-reveal">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">FAQ</h2>
          <div className="mm-faq-grid">
            {FAQ.map((f) => (
              <div className="mm-faq-item" key={f.q}>
                <span className="mm-faq-q">{f.q}</span>
                <span className="mm-faq-a">{f.a}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CLOSER LETTER */}
      <section className="mm-section mm-letter mm-reveal" id="letter">
        <div className="mm-wrap">
          <div className="mm-letter-body">
            <p className="mm-letter-lead">Dear trader,</p>
            <p>You buy the evaluation, you start clean — then one loss hits and your hand is already back on the mouse. Bigger size. Random stop. Daily limit gone. Buy another one. You've seen this movie, and you know how it ends, because you've paid for the ending several times.</p>
            <p className="mm-letter-punch">Another course won't fix that. Another Discord call won't either.</p>
            <p>Or maybe it isn't that at all. Maybe you can trade perfectly well — you just can't be at the screen at 9:30 because you have a job, a family, a life. Either way the account sits there needing someone to run it properly, and that someone keeps not being available.</p>
            <p className="mm-letter-punch">So we do it instead.</p>
            <p>You buy the evaluation and it stays in your name. Our desk trades it inside the firm's rules. The firm pays you, you keep <strong>{CLIENT_SPLIT}</strong>, and we invoice <strong>{OUR_SPLIT}</strong> out of money already sitting in your account. If no payout ever lands, we never earn a cent — which is the only incentive structure worth signing.</p>
            <p>We can't promise you'll pass. Anyone who does is lying to you: evaluations fail, markets do what they want, and rules get breached. What we can put in writing is what happens when it goes wrong — and we do, before you commit.</p>
            <div className="mm-letter-cta-wrap">
              <a href={APPLY_ANCHOR} className="mm-btn mm-btn-lg" onClick={() => track('CTAClick', 'cta_click', { source: 'letter' }, true)}>Send the questionnaire</a>
            </div>
          </div>
        </div>
      </section>

      <SiteFooter />

      <a href={APPLY_ANCHOR} className={`mm-sticky-cta${hideSticky ? ' is-hidden' : ''}`} onClick={() => track('CTAClick', 'cta_click', { source: 'sticky' }, true)}>Apply for management</a>
    </div>
  )
}
