// Forex Passing — "money" page (served at /meta and the funnel slugs).
//
// The offer: we run your prop-firm evaluation and manage the funded account.
// Nothing is sold here — the single conversion is the application questionnaire
// (#apply). No price, no checkout.
//
// Terms shown on this page come from constants.ts. Payout certificates come from
// src/data/payouts.ts, generated by bin/sync-payouts.mjs off Pro Traders Funding's
// public API — never hand-edited.

import { useEffect, useRef, useState } from 'react'
import { ApplyModal } from '../components/ApplyFlow'
import { TrackRecordModal } from '../components/TrackRecord'
import {
  CTA_LABEL,
  CLIENT_SPLIT,
  EVAL_DISCOUNT,
  EVAL_DISCOUNT_NOTE,
  GUARANTEE_CREDIT,
  OUR_SPLIT,
  PARTNER_FIRM,
  FORM_PREVIEW_LABEL,
  FORM_PREVIEW_PLACEHOLDER,
  PASS_WINDOW,
  REFUND_WINDOW,
  APPLY_ANCHOR,
} from '../constants'
import { FAQ } from '../data/faq'
import { PAYOUT_CERTS, PAYOUT_TOTALS } from '../data/payouts'
import { TESTIMONIALS } from '../data/testimonials'
import {
  AutoScroller,
  CertCard,
  HeroVsl,
  REVIEWS,
  ReviewBadge,
  ReviewCard,
  SiteFooter,
  TermsCard,
  TestimonialCard,
  TopBar,
  track,
  useReveal,
} from './shared'
import { PerformanceWidget } from '../components/PerformanceWidget'

const PAIN_STEPS = [
  'You buy the evaluation',
  'You start clean',
  'You take one loss',
  'Revenge mode',
  'One more click',
  'Random stop',
  'Daily loss blown',
  'Buy another one.',
]

// How the service runs, in order. Step 02 is the one nobody else puts in writing.
const HOW: [string, string, string][] = [
  ['01', 'You send the questionnaire', `A few questions about your firm, account size and where you are right now. Under a minute, costs nothing.${EVAL_DISCOUNT ? ` Accepted applicants buy the evaluation ${EVAL_DISCOUNT} cheaper through our partner link.` : ''}`],
  ['02', 'We check the firm rules', 'Before anything starts we confirm the firm allows a third party to trade the account. If it does not, we say so.'],
  ['03', 'Written management agreement', 'Risk limits, the split and how you exit, all on paper. Nobody touches an account until it is signed.'],
  ['04', 'We trade, you collect', 'Our desk runs the account inside the firm rules. Payouts are requested by you and land in your account.'],
]

// What the client keeps — replaces the old value stack. Deliberately no prices.
const CONTROL: { tag?: string; t: string; d: string }[] = [
  { tag: 'CORE', t: 'The account stays yours', d: `It is registered in your name, at your firm. We get trading access under the agreement, not ownership.` },
  { t: 'Payouts go straight to you', d: 'The firm pays you directly. Our share is invoiced afterwards, out of money already in your hands.' },
  { t: `You keep ${CLIENT_SPLIT}`, d: `Our share is ${OUR_SPLIT} of a released payout. That is the entire commercial relationship.` },
  { t: 'No subscription', d: 'Nothing monthly, nothing upfront to us. If nothing is paid out, there is nothing to split.' },
  ...(EVAL_DISCOUNT
    ? [{
        t: `You pay ${EVAL_DISCOUNT} less for the evaluation`,
        d: `You still buy it yourself, in your name. The discount comes off at the firm's checkout ${EVAL_DISCOUNT_NOTE}.`,
      }]
    : []),
  { t: 'You can watch every trade', d: 'Your platform login stays yours. Positions, orders and drawdown are visible to you in real time.' },
  { t: 'You can stop', d: 'The agreement sets a notice period and how access is revoked. Change the password and it ends.' },
]

const WHOFOR: [string, string][] = [
  ['Stuck in the reset loop', "You've bought more evaluations than you'd like to admit. Each one dies the same way, somewhere around day four."],
  ['Funded but fragile', 'You passed once. Now every session is a chance to lose it, and you trade smaller than the account deserves.'],
  ['No time to sit there', 'You can read a chart, but you have a job. The setups happen while you are in meetings.'],
]

const TICKER = [
  'Hands-free prop challenges',
  `You keep ${CLIENT_SPLIT} of the profit`,
  'Fee only after a real payout',
  EVAL_DISCOUNT ? `${EVAL_DISCOUNT} off your evaluation` : 'No subscription',
  'Written management agreement',
  'The account stays in your name',
  `${REFUND_WINDOW} guarantee`,
]

function TopTicker() {
  const items = [...TICKER, ...TICKER]
  const [hidden, setHidden] = useState(false)
  useEffect(() => {
    let last = window.scrollY
    const onScroll = () => {
      const y = window.scrollY
      if (y > 140 && y > last) setHidden(true)
      else if (y < last || y < 80) setHidden(false)
      last = y
    }
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])
  const check = (
    <span className="mm-ticker-ico" aria-hidden="true">
      <svg viewBox="0 0 24 24"><path d="M5 13l4 4L19 7" stroke="#fff" fill="none" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
    </span>
  )
  return (
    <div className={`mm-ticker${hidden ? ' mm-ticker-hidden' : ''}`} aria-label="Announcements">
      <div className="mm-ticker-track">
        {items.map((t, i) => (
          <span className="mm-ticker-item" key={t + i}>{check}{t}</span>
        ))}
      </div>
    </div>
  )
}

function endOfTodayMs() {
  const d = new Date()
  d.setHours(23, 59, 59, 999)
  return d.getTime()
}

// Daily-resetting urgency countdown on the application card.
// ⚠ Invented scarcity: it resets every midnight and is not tied to anything real.
// Kept by an explicit owner decision — remove it if the funnel ever needs to hold up
// to an ad-platform review.
function Countdown() {
  const target = useRef(endOfTodayMs())
  const [now, setNow] = useState(Date.now())
  useEffect(() => {
    const id = setInterval(() => setNow(Date.now()), 1000)
    return () => clearInterval(id)
  }, [])
  // Past midnight the captured target is in the past, and without this roll the
  // clamp below pins the display at 00:00:00 — which reads as "closed" sitting
  // directly above the form.
  if (now >= target.current) target.current = endOfTodayMs()
  let s = Math.max(0, Math.floor((target.current - now) / 1000))
  const h = String(Math.floor(s / 3600)).padStart(2, '0')
  s %= 3600
  const m = String(Math.floor(s / 60)).padStart(2, '0')
  const sec = String(s % 60).padStart(2, '0')
  return <span className="mm-count">{h}:{m}:{sec}</span>
}

/* ---------------------------------------------------------------------------
 * OFFER PAGE CHROME — modelled on the reference funnel: one repeated CTA, a
 * questionnaire that opens in a modal from anywhere, and a bar that stays on
 * screen the whole way down.
 * ------------------------------------------------------------------------- */

function CheckIcon() {
  return (
    <span className="mm-check-ico" aria-hidden="true">
      <svg viewBox="0 0 24 24"><path d="M5 13l4 4L19 7" /></svg>
    </span>
  )
}

function CheckRow({ title, detail }: { title: string; detail?: string }) {
  return (
    <div className="mm-check">
      <CheckIcon />
      <span className="mm-check-t">
        {title}
        {detail && <span className="mm-check-d">{detail}</span>}
      </span>
    </div>
  )
}

// The one button on the page. Every instance opens the same questionnaire.
function Cta({
  onOpen,
  source,
  className = '',
}: {
  onOpen: () => void
  source: string
  className?: string
}) {
  return (
    <button
      type="button"
      className={`mm-btn mm-btn-lg ${className}`}
      onClick={() => {
        track('CTAClick', 'cta_click', { source }, true)
        onOpen()
      }}
    >
      {CTA_LABEL}
    </button>
  )
}

function CtaRow({ onOpen, source, tight }: { onOpen: () => void; source: string; tight?: boolean }) {
  return (
    <div className={`mm-cta-center${tight ? ' mm-cta-center-tight' : ''}`}>
      <Cta onOpen={onOpen} source={source} />
    </div>
  )
}

// Low-friction entry point: the card looks like the first field of the form, and
// the field opens the questionnaire rather than collecting anything itself.
//
// Read-only on purpose. Tapping it means "I want to fill this in", so the
// questionnaire opens there and then — it asks for the name itself, and a name
// typed twice is a name typed once too many. Read-only also keeps the phone
// keyboard from flashing open and shut behind the modal. Focus is the only
// handler needed: a read-only field still takes focus from a tap, a click and
// the Tab key alike, so one listener covers every way in.
function FormPreview({ onOpen }: { onOpen: (name: string) => void }) {
  const open = (source: string) => {
    track('CTAClick', 'cta_click', { source }, true)
    onOpen('')
  }
  return (
    <form
      className="mm-preview"
      onSubmit={(e) => {
        e.preventDefault()
        open('preview')
      }}
    >
      <span className="mm-preview-label">
        <span className="mm-preview-dot" aria-hidden="true" />
        {FORM_PREVIEW_LABEL}
      </span>
      <input
        className="mm-preview-input"
        type="text"
        name="name"
        autoComplete="name"
        placeholder={FORM_PREVIEW_PLACEHOLDER}
        value=""
        readOnly
        aria-haspopup="dialog"
        aria-label="Your full name, opens the application"
        onFocus={(e) => {
          e.currentTarget.blur()
          open('preview_field')
        }}
      />
      <button type="submit" className="mm-btn mm-btn-lg mm-btn-full">{CTA_LABEL}</button>
    </form>
  )
}

export function MoneyPage() {
  const rootRef = useRef<HTMLDivElement>(null)
  // Doubled so the marquee wraps seamlessly. Empty array = section not rendered.
  const cards = [...PAYOUT_CERTS, ...PAYOUT_CERTS]
  const reviewRows = [
    [...REVIEWS, ...REVIEWS],
    [...[...REVIEWS].reverse(), ...[...REVIEWS].reverse()],
  ]

  useReveal(rootRef)

  // A visitor arriving from a partner link lands here as /meta?ref=<slug>.
  // Park it so the questionnaire can credit the referral even if they read the
  // whole page first, or come back later.
  useEffect(() => {
    const ref = new URLSearchParams(window.location.search).get('ref')
    if (ref && /^[a-z0-9][a-z0-9-]{2,31}$/.test(ref)) {
      try {
        window.localStorage.setItem('fp_ref', ref)
      } catch {
        // Private mode or storage disabled — attribution is best-effort.
      }
    }
  }, [])

  useEffect(() => {
    // No value/currency — nothing is sold on this page, the conversion is a Lead.
    track('ViewContent', 'view_content', { content_name: 'Account management' })
    const fired = new Set<number>()
    const onScroll = () => {
      const max = document.documentElement.scrollHeight - window.innerHeight
      if (max <= 0) return
      const pct = Math.round((window.scrollY / max) * 100)
      for (const t of [25, 50, 75, 100]) {
        if (pct >= t && !fired.has(t)) {
          fired.add(t)
          track('ScrollDepth', 'scroll_depth', { percent: t }, true)
        }
      }
    }
    window.addEventListener('scroll', onScroll, { passive: true })
    return () => window.removeEventListener('scroll', onScroll)
  }, [])

  // The questionnaire lives in a modal so every button on the page opens the
  // same thing, wherever the reader happens to be. The preview card passes the
  // name it collected; every other entry point opens it empty.
  const [trackOpen, setTrackOpen] = useState(false)
  const [applyOpen, setApplyOpen] = useState(false)
  const [applyName, setApplyName] = useState('')
  const openApply = (name = '') => {
    setApplyName(name)
    setApplyOpen(true)
  }

  // Every CTA elsewhere on the site points here at /meta#apply. On its own that
  // only scrolled the reader to a card they then had to tap, which is a step
  // nobody asked for: they already pressed a button that said "apply". So the
  // link opens the questionnaire on arrival. ?apply=1 does the same, because ad
  // networks and link shorteners drop the fragment often enough to matter.
  useEffect(() => {
    const wanted =
      window.location.hash === APPLY_ANCHOR ||
      new URLSearchParams(window.location.search).get('apply') === '1'
    if (!wanted) return
    openApply()
    // Leave the address without the trigger, so a reload or a back-and-forward
    // does not spring the panel open again.
    window.history.replaceState(null, '', window.location.pathname + window.location.search.replace(/([?&])apply=1&?/, '$1').replace(/[?&]$/, ''))
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // The sticky bar steps aside while the application section is on screen.
  // Otherwise it sits on top of the very card it is pointing at: on a phone it
  // covers the note under the form, on a 844px-tall screen it clips the card's
  // own button, and either way the reader gets the same green "LET'S START NOW"
  // twice at once.
  const [hideSticky, setHideSticky] = useState(false)
  useEffect(() => {
    const apply = document.getElementById('apply')
    if (!apply || !('IntersectionObserver' in window)) return
    const io = new IntersectionObserver((entries) => setHideSticky(entries[0].isIntersecting), {
      // Only once the section reaches the bar, not the moment it appears.
      rootMargin: '0px 0px -84px 0px',
      threshold: 0,
    })
    io.observe(apply)
    return () => io.disconnect()
  }, [])

  return (
    <div className="mm-root" ref={rootRef}>

      <TopTicker />
      <TopBar />

      {/* HERO — message-matched to the ad: we trade it, you own it */}
      {/* One column, centred, laid out like the reference funnel: the headline
          says what we do, the warning kills the two objections that stop people
          reading, and the video is the next thing under their thumb. */}
      <section className="mm-hero mm-hero-solo" id="top">
        <div className="mm-wrap">
          <span className="mm-eyebrow mm-eyebrow-teal mm-eyebrow-c">Prop account management</span>
          <h1 className="mm-h1 mm-h1-solo">
            WE PASS YOUR CHALLENGE &amp; MANAGE YOUR ACCOUNT <span className="mm-teal">FOR YOU</span>
          </h1>
          <p className="mm-warn mm-warn-hero">
            You don't need any experience at all, and you pay us nothing up front. You buy a prop
            firm evaluation{EVAL_DISCOUNT ? `, ${EVAL_DISCOUNT} cheaper through our partner link,` : ','} and
            that is the account we manage for you. The video below walks through it.
          </p>
          <HeroVsl badge="Start here" title="Watch this 120 second video" source="meta_hero" />
          <div className="mm-cta-row mm-cta-center-row">
            <Cta onOpen={openApply} source="hero" />
            <a href="#fix" className="mm-btn mm-btn-ghost mm-btn-lg">See how it works</a>
          </div>
          <p className="mm-microtrust">Nothing to pay on this page · Questionnaire first · Firm rules checked before we start</p>
        </div>
        <div className="mm-hero-glow" aria-hidden="true" />
      </section>

      {/* HOW IT WORKS */}
      <section className="mm-section mm-mech mm-reveal" id="fix">
        <div className="mm-wrap">
          <span className="mm-eyebrow mm-eyebrow-teal mm-eyebrow-c">How it works</span>
          <h2 className="mm-h2 mm-center">Four steps, <span className="mm-teal">in this order</span></h2>
          <p className="mm-lead mm-lead-mid mm-center">
            Nothing is signed before step two, and nobody logs into anything before step three.
          </p>

          <div className="mm-steps">
            {HOW.map(([n, t, d]) => (
              <div className="mm-step" key={n}>
                <span className="mm-step-n">{Number(n)}</span>
                <span className="mm-step-t">{t}</span>
                <span className="mm-step-d">{d}</span>
              </div>
            ))}
          </div>

          <p className="mm-mech-note">
            An evaluation usually takes around <strong>{PASS_WINDOW}</strong>. It can take longer,
            and it can fail. That is what the guarantee below is for.
          </p>

          <CtaRow onOpen={openApply} source="how" />
        </div>
      </section>

      {/* STATEMENT BAND */}
      <section className="mm-band mm-reveal">
        <div className="mm-wrap">
          <p className="mm-band-text">NO PAYOUT. NO FEE.</p>
          <p className="mm-band-sub">We are paid out of released payouts, not out of your intention to try.</p>
        </div>
      </section>

      {/* PAYOUT CERTIFICATES — real records from the partner firm's public API */}
      {/* Proof sits directly under the claim, before the terms and before the
          form. It used to sit after the form, where the reader who stopped at
          "why should I believe you" never reached it. */}
      {cards.length > 0 && (
        <section className="mm-section mm-payouts mm-reveal" id="payouts">
          <div className="mm-wrap">
            <h2 className="mm-h2 mm-center">THIS IS WHAT OUR CLIENTS WALK AWAY WITH</h2>
            <p className="mm-lead mm-center mm-lead-mid">
              Certificates {PARTNER_FIRM} issued to our clients: payouts released, evaluations
              passed, accounts funded. Scan any of them and the firm confirms it.
            </p>
          </div>

          <AutoScroller className="mm-scroller-cert" ariaLabel="Payout certificates" speed={0.55}>
            {cards.map((c, i) => (
              <CertCard cert={c} key={c.trader + c.date + c.amount + i} />
            ))}
          </AutoScroller>

          <div className="mm-wrap">
            <p className="mm-disclaimer">
              Certificates issued by {PARTNER_FIRM} to Forex Passing clients, pulled live from the
              firm's public record. Individual results vary. An evaluation can fail and no outcome is
              guaranteed.
            </p>
            <CtaRow onOpen={openApply} source="payouts" />
          </div>
        </section>
      )}

      {/* CLIENT TESTIMONIALS — see the warning at the top of data/testimonials.ts.
          The slots stay on the page while the clips are being recorded: each one
          says so rather than pretending to be a player. Drop a YouTube id into
          the entry and that card becomes the real thing. */}
      {TESTIMONIALS.length > 0 && (
        <section className="mm-section mm-testi mm-reveal" id="testimonials">
          <div className="mm-wrap">
            <h2 className="mm-h2 mm-center">CLIENT TESTIMONIALS</h2>
            {/* Until a clip is published the page must not promise footage that
                is not there. The short version is written out either way. */}
            <p className="mm-lead mm-center mm-lead-mid">
              {TESTIMONIALS.some((t) => t.videoId)
                ? 'The short version is written under each video.'
                : 'The recordings are being filmed. The short version of each one is written underneath.'}
            </p>

            {/* Keyed by position, not by name: a reserved slot has no name, so
                keying on one collides the moment there is more than one. */}
            <div className="mm-testi-grid">
              {TESTIMONIALS.map((t, i) => (
                <TestimonialCard testimonial={t} key={t.videoId || `slot-${i}`} />
              ))}
            </div>

            <p className="mm-disclaimer" style={{ marginTop: 26 }}>
              Individual results. Past performance is not indicative of future results, an
              evaluation can fail, and no outcome is guaranteed.
            </p>
          </div>
        </section>
      )}

      {/* WHAT YOU KEEP CONTROL OF */}
      <section className="mm-section mm-system mm-reveal" id="inside">
        <div className="mm-wrap">
          <span className="mm-eyebrow mm-eyebrow-teal mm-eyebrow-c">Your side of the deal</span>
          <h2 className="mm-h2 mm-center">What you <span className="mm-teal">keep control of</span></h2>
          <p className="mm-lead mm-lead-mid mm-center">
            The terms are short on purpose. Read them before you apply, not after.
          </p>

          {/* The list and the card say the same thing at two levels of detail,
              so they sit side by side rather than one after the other: the card
              reads as the summary of the list next to it instead of a second
              thing to scroll past. Stacks back under 980px. */}
          <div className="mm-control-grid">
            <div className="mm-checks">
              {CONTROL.map((c) => (
                <CheckRow title={c.t} detail={c.d} key={c.t} />
              ))}
            </div>

            {/* Was in the hero. It belongs with the terms it summarises, and the
                hero is now a single centred column like the reference funnel. */}
            <div className="mm-terms-slot">
              <TermsCard />
            </div>
          </div>
        </div>
      </section>

      {/* APPLICATION — the only conversion on the page */}
      <section className="mm-section mm-pricing mm-reveal" id="apply">
        <div className="mm-wrap">
          <div className="mm-price-proof" role="list" aria-label="Proof">
            <span className="mm-price-proof-item" role="listitem"><strong>4.9/5</strong> from 500+ traders</span>
            <span className="mm-price-proof-sep" aria-hidden="true" />
            {PAYOUT_TOTALS && (
              <>
                <span className="mm-price-proof-item" role="listitem">
                  <strong>{PAYOUT_TOTALS.totalUsd}</strong> released at {PARTNER_FIRM}
                </span>
                <span className="mm-price-proof-sep" aria-hidden="true" />
              </>
            )}
            <span className="mm-price-proof-item" role="listitem"><strong>{CLIENT_SPLIT}/{OUR_SPLIT}</strong> split, paid after payout</span>
          </div>

          {/* ⚠ Invented scarcity, kept by an explicit owner decision. */}
          <p className="mm-warn mm-warn-mb">
            We don't have many spots left. Today's applications close in <Countdown />
          </p>

          <FormPreview onOpen={openApply} />

          <p className="mm-disclaimer" style={{ marginTop: 22 }}>
            Four questions and your contact details, about a minute. Nothing to pay. The rule check comes
            first, then a call, then the agreement.
          </p>
        </div>
      </section>

      {/* VERIFIED REVIEWS — Trustpilot-style */}
      <section className="mm-reviews mm-reveal" id="reviews">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center mm-reviews-h">OUR VERIFIED REVIEWS</h2>
          <ReviewBadge onDark />
          <p className="mm-reviews-sub">Rated <strong>4.9</strong> out of 5 based on <strong>500+</strong> reviews</p>
        </div>
        {reviewRows.map((row, ri) => (
          <AutoScroller className="mm-scroller-rev" key={ri} reverse={ri === 1} speed={0.32} lock>
            {row.map((r, i) => (
              <ReviewCard review={r} key={r.name + i} />
            ))}
          </AutoScroller>
        ))}
      </section>

      {/* OUR GUARANTEES */}
      <section className="mm-guar mm-reveal" id="guarantees">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">OUR <span className="mm-teal">GUARANTEES</span></h2>
          <p className="mm-lead mm-lead-mid mm-center">
            Straightforward protection, so you know exactly where you stand.
          </p>
          <div className="mm-checks">
            <CheckRow
              title="If we lose your account, the next evaluation is on us."
              detail="We buy it, at the same size, and trade it under the same agreement. That is clause 5(c), not a line on a landing page."
            />
            <CheckRow
              title={`Or take your money back, plus a ${GUARANTEE_CREDIT} service credit.`}
              detail="Your choice, not ours. A losing evaluation that stayed inside the firm's rules is not a breach; markets do that, and no service can promise otherwise."
            />
            <CheckRow
              title={`${REFUND_WINDOW} to decide, on either remedy.`}
              detail="The exact wording is in the management agreement. Read it before you sign, not after."
            />
          </div>
          <CtaRow onOpen={openApply} source="guarantees" />
        </div>
      </section>

      {/* VERIFIED PERFORMANCE — myfxbook-style interactive widget */}
      <section className="mm-section mm-perf mm-reveal" id="performance">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">VERIFIED RESULTS</h2>
          <p className="mm-lead mm-center mm-lead-mid">
            How managed accounts are run over time: equity curve, monthly returns and the trade
            log behind them. Past performance does not predict future results.
          </p>

          <PerformanceWidget />

          <div className="mm-cta-center">
            <button
              type="button"
              className="mm-btn mm-btn-ghost mm-btn-lg"
              onClick={() => {
                track('CTAClick', 'cta_click', { source: 'track_record' }, true)
                setTrackOpen(true)
              }}
            >
              See the full track record
            </button>
          </div>
          <CtaRow onOpen={openApply} source="performance" tight />
        </div>
      </section>

      {/* FAQ */}
      <section className="mm-section mm-faq mm-reveal">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">FREQUENTLY ASKED QUESTIONS</h2>
          <p className="mm-lead mm-lead-mid mm-center">
            Guarantees, fees and how we work. Straight answers, including the ones that are a no.
          </p>
          <div className="mm-acc">
            {FAQ.map((f) => (
              <details className="mm-acc-item" key={f.q}>
                <summary>{f.q}</summary>
                <p className="mm-acc-a">{f.a}</p>
              </details>
            ))}
          </div>
          <CtaRow onOpen={openApply} source="faq" />
        </div>
      </section>

      {/* STAT HOOK */}
      <section className="mm-stathook">
        <div className="mm-wrap">
          <p className="mm-stathook-big">8</p>
          <p className="mm-stathook-text">
            steps. That's all it takes to blow an evaluation, and most traders run the exact same
            eight, every time, then buy another one. Not because they can't read a chart. Because
            sitting there alone with your own money on the line does something to your hands.
          </p>
        </div>
      </section>

      {/* PAIN */}
      <section className="mm-section mm-pain mm-reveal" id="problem">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">THE LOOP</h2>
          <div className="mm-pain-steps">
            {PAIN_STEPS.map((s, i) => (
              <div className={`mm-pain-step${i === PAIN_STEPS.length - 1 ? ' mm-pain-step-last' : ''}`} key={s}>
                <span className="mm-pain-n">{String(i + 1).padStart(2, '0')}</span>
                <span className="mm-pain-t">{s}</span>
              </div>
            ))}
          </div>
          <p className="mm-pain-note">
            It is not a knowledge problem. Nobody blows an account because they never heard of a
            stop loss.
          </p>
        </div>
      </section>

      {/* WHO IT'S FOR */}
      <section className="mm-section mm-whofor mm-reveal">
        <div className="mm-wrap">
          <h2 className="mm-h2 mm-center">IS THIS YOU?</h2>
          <div className="mm-whofor-grid">
            {WHOFOR.map(([t, d]) => (
              <div className="mm-whofor-card" key={t}>
                <span className="mm-whofor-t">{t}</span>
                <span className="mm-whofor-d">{d}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CLOSER LETTER — long-form, in the rhythm of a letter rather than an
          essay: short stacked lines, asides in italics, the punch lines given
          their own breathing room. */}
      <section className="mm-section mm-letter mm-reveal" id="letter">
        <div className="mm-wrap">
          <div className="mm-letter-body">
            <h2 className="mm-letter-lead">Dear trader,</h2>

            <p>We get it.</p>

            <p>
              Passing a prop firm evaluation is hard.<br />
              Really hard.
            </p>

            <p>
              You're probably staring at a chart right now wondering whether this trade is the one
              that finally blows the account… or saves it.
            </p>

            <p>
              Sleeping badly.<br />
              Heart going during the London open.<br />
              Second-guessing every entry, every stop, every exit.
            </p>

            <p>And on top of all that…</p>

            <p className="mm-letter-punch">You're being pulled in fifteen directions at once.</p>

            <p className="mm-letter-aside">"Right. Okay. Think."</p>

            <p>
              Should I revenge trade it back?<br />
              Switch strategy?<br />
              Buy another course?<br />
              Join another Discord?<br />
              Trade the news? Avoid the news?<br />
              Size up? Size down?
            </p>

            <p>And the firms themselves?</p>

            <p className="mm-letter-aside">Everyone has an opinion about prop firms.</p>

            <p>New rules. New drawdown maths. New ways to fail.</p>

            <p>
              Pay another fee?<br />
              Reset the account?<br />
              Start over… again?
            </p>

            <p className="mm-letter-aside">somebody please take the mouse away from me</p>

            <p>Look, most traders aren't bad traders.</p>

            <p className="mm-letter-punch">They're overloaded.</p>

            <p>
              A bit of overtrading,<br />
              mixed with decisions made at the worst possible moment,<br />
              and a sprinkle of "this one <em>has</em> to work."
            </p>

            <p>
              So they do a little of this…<br />
              a little of that…
            </p>

            <p>
              Until they're staring at the screen wondering how a green day turned red in ten
              minutes.
            </p>

            <p>
              We call that cycle <span className="mm-teal">the loop</span>.
            </p>

            <p className="mm-letter-aside">You've met it. Probably paid for it more than once.</p>

            <p>
              It's stressful.<br />
              It's exhausting.<br />
              And it is exactly how prop firms make their money.
            </p>

            <p>We'd rather trade with discipline and a written process than keep feeding that.</p>

            <hr className="mm-letter-rule" />

            <p>But this isn't about us… it's about <strong>you</strong>.</p>

            <p>You're reading this because, in some shape or form:</p>

            <ul className="mm-letter-list">
              <li>You're tired of failing evaluations</li>
              <li>Or tired of holding a funded account together under pressure</li>
              <li>Or tired of doing everything right… and still not getting paid</li>
            </ul>

            <p>
              Or maybe you can trade perfectly well,<br />
              you just can't be at the screen at half past two because you have a job, a family,
              a life.
            </p>

            <p className="mm-letter-punch">What you actually want:</p>

            <p>
              More payouts.<br />
              More consistency.<br />
              More peace of mind.
            </p>

            <p className="mm-letter-big">
              <span className="mm-teal">More time back.</span>
            </p>

            <p>Away from the charts.</p>

            <p>Money landing in your account without babysitting a position all day.</p>

            <hr className="mm-letter-rule" />

            <p className="mm-letter-punch">That's where we come in.</p>

            <p>
              We pass and manage prop firm accounts for you,{' '}
              <span className="mm-teal">completely hands-off</span>.
            </p>

            <p>
              You keep <span className="mm-letter-num mm-teal">{CLIENT_SPLIT}</span> of the profit.<br />
              We take <strong>{OUR_SPLIT}</strong>, and only once you've been paid.
            </p>

            <p className="mm-letter-punch">And here's the part nobody else puts in writing:</p>

            <div className="mm-letter-box">
              <p>
                If we lose the account on our own rule breach →{' '}
                <span className="mm-teal">
                  you get back every fee you paid us, plus {GUARANTEE_CREDIT} on top.
                </span>
              </p>
              <p>
                Plus a guarantee that runs <span className="mm-teal">{REFUND_WINDOW}</span>, written
                into the agreement before you sign it.
              </p>
            </div>

            <p>
              No monthly fee.<br />
              No fee for trying.<br />
              No fee at all until a payout has actually landed with you.
            </p>

            <p>You bring the account.</p>

            <p className="mm-letter-punch">We bring the discipline, the execution and the boring consistency.</p>

            <p>
              And no, we can't promise you'll pass. Anyone promising that is lying to you:
              evaluations fail, markets do what they want, rules get breached. What we can promise
              is that what happens then is written down <em>before</em> you commit, not explained
              afterwards.
            </p>

            <p>
              Whatever your goal is, it starts the same way: by letting someone else trade the
              account, so you can finally{' '}
              <span className="mm-teal">enjoy the payout</span> instead of chasing it.
            </p>

            <p className="mm-letter-sign">The Forex Passing desk</p>

            <CtaRow onOpen={openApply} source="letter" />
          </div>
        </div>
      </section>

      <SiteFooter variant="meta" />

      {/* One step, visible the whole way down the page — except over the form. */}
      <div className={`mm-sticky-bar${hideSticky ? ' is-hidden' : ''}`}>
        <Cta onOpen={openApply} source="sticky" />
      </div>

      {trackOpen && <TrackRecordModal onClose={() => setTrackOpen(false)} />}

      {applyOpen && (
        <ApplyModal initialName={applyName} source="money" onClose={() => setApplyOpen(false)} />
      )}
    </div>
  )
}
